### ISSUE TITLE
Generalized arithmetic operator overloading

### ISSUE THREAD

**Issue by intellifactory-bb** [dotnet-websharper/websharper#102]
Allow F#-compatible overloading of arithmetic operators. See Vector example:

http://cs.hubfs.net/topic/Some/0/76105

---
- Bitbucket: https://bitbucket.org/intellifactory/websharper/issue/102
- Originally reported by: [IntelliFactory](http://bitbucket.org/IntelliFactory)
- Originally created at: 2013-01-14T20:01:14.645

**Comment by Tarmil** [comment]
Currently the following:

```fsharp
[<JavaScript>]
type Vector(values : float[]) =
    member v.Values = values
    member v.Length = values.Length
    member v.Item i = values.[i]
    static member ( + )(m: Vector,k: Vector) = Vector(Array.map2 (fun v1 v2 -> v1+v2) m.Values k.Values)

let v1 = Vector([|1.; 2.|])
let v2 = Vector([|3.; 4.|])
let v3 = v1 + v2
```

compiles the `v3` definition as `v1.add(v2)`. We should investigate.

**Comment by cgravill** [comment]
Is the generalised form now easier to implement in Zafir/4.x? We run into this somewhat often where someone comfortable in F# implements an algorithm using operator overloading. It then leads to a mixture of compile-time failures and run-time failures with e.g. the ( + ) operator.

In our 3.x branch we've tried workarounds to avoid built-in operators:

```fsharp
static member ( <+> )(m: Vector,k: Vector) = Vector(Array.map2 (fun v1 v2 -> v1+v2) m.Values k.Values)
```
in 3.x that fails with:
```
error FS0458: Quotations cannot contain expressions that make member constraint calls, or uses of operators that implicitly resolve to a member constraint call
```
whereas Zafir.4.0.133.15-beta4, looks more hopeful with
```
error : TODO: TraitCall with multiple source types
```
Note that the full workaround we currently use does work in both 3.x and 4.0.133.15-beta4:

```fsharp
type Vector(values : float[]) =
  member v.Values = values
  member v.Length = values.Length
  member v.Item i = values.[i]
  //static member ( <+> )(m: Vector,k: Vector) = Vector(Array.map2 (fun v1 v2 -> v1+v2) m.Values k.Values)

  let (<+>) (m: Vector) (k: Vector) = Vector(Array.map2 (fun v1 v2 -> v1+v2) m.Values k.Values)
```

It's quite far from the code we'd like to write to match the scientific publication we do. Any increased support for implementing math in F# and generation of JavaScript would be really helpful.

**Comment by Jand42** [comment]
This is now fully supported in WebSharper 4.1, multiple source types are handled by trying to look up the member in order, same as F# compiler does.
