### ISSUE TITLE
Native JS and async

### ISSUE THREAD

**Issue by intellifactory-bb** [dotnet-websharper/websharper#138]
The function Async.FromContinuations is not compatible with the native JS calling conventions. Consider the following example:

```
#!fsharp

    [<Inline "$cb(null,55)">]
    let wrapFun (cb : obj*obj->unit) = ()

    [<JavaScript>]
    let runEx () =
        async{
            let! (res,res1) = Async.FromContinuations (fun (ok,_,_) -> wrapFun ok)
            JavaScript.Log res1
            return ()
            } |> Async.Start

    runEx ()
```

This program should write 55 to the console but instead crashes with the following exception: "Uncaught TypeError: Cannot read property '1' of null"

The problem could reside around the following fact, consider the program:

```
#!fsharp

    [<Inline "$cb(\"should print\",55)">]
    let wrapFun (cb : obj*obj->unit) = ()

    [<JavaScript>]
    let runEx () =
        async{
            let! (res,res1) = Async.FromContinuations (fun (ok,_,_) -> wrapFun ok)
            JavaScript.Log res
            JavaScript.Log res1
            return ()
            } |> Async.Start

    runEx ()
```

This will log "s" then "h" to the console. For some reason the string seems to be interpreted in a wrong way when converted to a tuple.

---
- Bitbucket: https://bitbucket.org/intellifactory/websharper/issue/138
- Originally reported by: [neto_gallo](http://bitbucket.org/neto_gallo)
- Originally created at: 2013-08-12T15:28:21.468

**Comment by Jand42** [comment]
This is not a bug, the confusion here was with `[<Inline "$cb(null,55)">]`. F# functions passed around as a value are translated to JavaScript as 0/1-length functions (taking an array if the argument is a tuple in F#). WebSharper 4 introduces a non-intrusive optimization for this, but only if the function does not have an `Inline`.
