### ISSUE TITLE
"use strict" - strict mode

### ISSUE THREAD

**Issue by intellifactory-bb** [dotnet-websharper/websharper#227]
Sounds like this is something we should consider, as it improves performance and hsa better semantics:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions_and_function_scope/Strict_mode

---
- Bitbucket: https://bitbucket.org/intellifactory/websharper/issue/227
- Originally reported by: Anton Tayanovskyy
- Originally created at: 2014-03-29T19:13:24.231

**Comment by Jand42** [comment]
WebSharper 4 now uses strict mode. When writing JS, local functions are reorganized as needed, and all reserved keywords are respected by the variable name disambiguator.
