### ISSUE TITLE
Optimizer problem (eta-reduction)

### ISSUE THREAD

**Issue by intellifactory-bb** [dotnet-websharper/websharper#241]
``` fsharp
 | Lambda (None, [x], Application (f, [Var y])) ->
            if x = y && isPure f then f else expr
```

This is not correct in the case when `f` contains `x`.

---
- Bitbucket: https://bitbucket.org/intellifactory/websharper/issue/241
- Originally reported by: Anton Tayanovskyy
- Originally created at: 2014-05-07T16:05:32.196

**Comment by Jand42** [comment]
This is now working in both WebSharper 3.x and 4.x (both use two versions of `isPure`).
