### ISSUE TITLE
Packager problem with late-bound variables

### ISSUE THREAD

**Issue by intellifactory-bb** [dotnet-websharper/websharper#242]
Code responsible for packaging JS modules has problems when bindings are evaluated too early. Currently, eta-expansion converts `(fun x -> g x)` to `g`, so in the package we get `{someBinding: g}`, but `g` refers to late-bound variables, causing a problem. This is making #240 fail.

---
- Bitbucket: https://bitbucket.org/intellifactory/websharper/issue/242
- Originally reported by: Anton Tayanovskyy
- Originally created at: 2014-05-07T16:07:18.648

**Comment by Jand42** [comment]
This is now working in both WebSharper 3.x and 4.x.
