### ISSUE TITLE
Reference equality needed

### ISSUE THREAD

**Issue by intellifactory-bb** [dotnet-websharper/websharper#268]
Reference equality semantics are actually frequently very useful. Currently W# does not distinguish types with reference equality, although this should be quite easy to infer. As a result, you get annoying things like:

``` fsharp
obj () = obj () ==> true
```

And also deep non-terminating structural comparisons where you don't want it.

Reference equality is a pattern, you _want_ to have it sometimes. Currently in W# this requires verbose workarounds like setting a field to a uniquely generated int. Would be much better to have it work exactly as in F#.

---
- Bitbucket: https://bitbucket.org/intellifactory/websharper/issue/268
- Originally reported by: Anton Tayanovskyy
- Originally created at: 2014-07-31T17:43:35.422

**Comment by Jand42** [comment]
Classes now use reference equality in WebSharper 4, supporting overloading `Equals` and implementing `IEquatable` and `IComparable`.
