### ISSUE TITLE
Member overload fails during compilation.

### ISSUE THREAD

**Issue by FrankBro** [dotnet-websharper/websharper#593]
`Unexpected code transformation error` is raised when compiling along with `Failed to compile assembly with WebSharper.` when a member overload is present in a module with the `JavaScript` attribute. 

Here is a simple example:

``` fsharp
type JQuery
with
    [<Inline "$0.date()">]
    member this.Date () = X<Date option>

    [<Inline "$0.date($date)">]
    member this.Date (date: Date) = X<unit>
```

**Comment by Jand42** [comment]
Yes, this seems to be a bug in inling F#-style overloaded extension members.

I have tested, WebSharper 3 handles the C#-style definition properly:

```fsharp
open System.Runtime.CompilerServices

[<Extension>]
type JQueryExtension =
    [<Extension; Inline "$0.date()">]
    static member Date (this: JQuery) = X<Date option>

    [<Extension; Inline "$0.date($date)">]
    static member Date (this: JQuery, date: Date) = X<unit>
```

WebSharper 4 beta translates both versions correctly.

**Comment by FrankBro** [comment]
Good enough for me. Thank you!

**Comment by Jand42** [comment]
This is now working in WebSharper 4.
