### ISSUE TITLE
Extending C# sitelets with a custom router

### ISSUE THREAD

**Issue by Jooseppi12** [dotnet-websharper/websharper#714]
https://github.com/intellifactory/websharper.docs/blob/master/Sitelets.md#advanced-sitelets

In F# it's easy to create a custom router for Sitelets as it's seen above, however C# currently lacks a similar feature.

**Comment by Jand42** [comment]
This has now been addressed in WebSharper 4.1, documented in https://github.com/dotnet-websharper/docs/blob/master/v4.1/csharp/sitelets.md
