### ISSUE TITLE
Multiple Endpoint attributes

### ISSUE THREAD

**Issue by Jand42** [dotnet-websharper/websharper#871]
Allow multiple `Endpoint` attributes on types, union cases and fields to be handled by `Router.Infer`. The first one would be used for writing the URL, and the all of them are used for parsing.

Optionally, there could be a variant of `Sitelet.Infer` that automatically returns a redirect response whenever the URL is not in the canonical form (using only first occurences of `EndPoint`).

**Comment by granicz** [comment]
The point here would be to enable a declarative notation for different, but semantically equivalent (thus, carrying the same arguments, etc.) URLs that are mapped to the same underlying endpoint value. A shorter notation would be:

`[<EndPoint("/", "/home", "/main")>]`

As for how to route secondary URLs, we should carefully consider client caching and upcoming standards such as HTTP/2's server push.

**Comment by Jand42** [comment]
@granicz Good point about the multiple arguments equivalent to multiple attributes.

Server push is an opt-in feature in server-side code, currently not done automatically by WebSharper for anything. Even if support is added, it is not directly related to routing itself but how the result of a parse is handled in a Sitelet. The only related optimization that routing could have is to optionally track in the parse result if the URL was canonical (always using first option) or not, otherwise deciding this needs the parsed endpoint to be written back to a link to compare.

**Comment by Jand42** [comment]
Related C# concern: if a base type has multiple ways of parsing, then doing a forward-only parse on the inheritance chain is most efficient, generating a direct product could be big if there are multiple levels with multiple options.

But opting out of parsing inherited fields as determined by the base class should also be useful. For example having `EndPoint("/blog/{BlogId}")` and `EndPoint("/article/{BlogId}/{ArticleId}", inheritRoute = false)` on a subclass, where the `false` argument specifies that Endpoint string of the base class should be ignored and completely replaced by the new pattern.

**Comment by Jand42** [comment]
Also uncovered during this effort: HTTP methods were not handled for C# classes so far. They should work as their F# counterparts, for example:

```csharp
[EndPoint("GET /article/{id}/{comment}")]
```

**Comment by Jand42** [comment]
.NET is not preserving attribute ordering, so a for specifying order of `Endpoint` parsing, an `order` parameter is needed. When using variable arguments with a single attribute, the order is as passed.

Currently there is an FCS issue that an attribute with a `ParamArray` constructor argument used in a C# project fails to be deserialized. So for example, if `EndPoint("/", "/home")` is used on a C# class, then `Router.Infer` is used on that type from F# (either directly, or it being used inside an F# type), then the compiler fails. Workaround is to use multiple `EndPoint` attributes in this case.

**Comment by V0d01ey** [comment]
Please, correct the documentation accordingly about requiring {} in endpoint mask
```
[EndPoint("GET /article/{id}/{comment}")]
```
From documentation:
```
[EndPoint("/test")]
class T
{
    int number;
    string name;
}

SiteletBuilder().With<T>(/* ... */)

// Accepted Request:    GET /test/1/abc
// Parsed Endpoint:     new EndPoint { number = 1, name = "abc" }
```

**Comment by Jand42** [comment]
@V0d01ey Thanks for the notice, done in https://github.com/dotnet-websharper/docs/commit/496f4d195e6c20662383d37b962914e5f5c297f9. You can also report documentation problems and submit PRs at https://github.com/dotnet-websharper/docs
