### ISSUE TITLE
Json.Serialize fails for maps that have complex type  keys

### ISSUE THREAD

**Issue by cata** [dotnet-websharper/websharper#883]
See http://try.websharper.com/snippet/0000Hy

Serializing maps (and perhaps dictionaries in general) as arrays of tuples would remove this limitation.

At the moment we are working around this by performing the above conversion ourselves, but this approach affects application semantics  and introduces ugly boilerplate code. 

Ideally all valid F# maps would serialize/deserialize correctly.

**Comment by Tarmil** [comment]
Thanks for the report, I am looking into it now. Looks like Json.Serialize doesn't like [the way empty tree nodes are stored as null](https://github.com/dotnet-websharper/websharper/blob/master/src/stdlib/WebSharper.Collections/BalancedTree.fs#L41-L51); I can replace these inlines with proper erased options that Json.Serialize can handle.

**Comment by cata** [comment]
@Tarmil - thank you, it would be awesome to have this working!

**Comment by Jand42** [comment]
This was breaking `Set.empty` sent to an RPC, fix is easy. But `deserialize map with complex key type` test is also failing, even when using `(Json.Deserialize (Json.Serialize x))`. Optimally there should be a separate test for serialization so that the exact format of how a `Map` with a non-string key is serialized is tested.

**Comment by Jand42** [comment]
Test `Client to Sitelet JSON round-trip: map with complex keys` fails with `Error during RPC JSON conversion` on  the server.

**Comment by cata** [comment]
@Tarmil, @Jand42  - thank you for this, I can confirm set and map serialization is now working.
