### ISSUE TITLE
JavaScript implementation of balanced trees is broken in 4.1.2

### ISSUE THREAD

**Issue by cata** [dotnet-websharper/websharper#885]
Removing the first element in a map or set yields and empty map/set.
Repro: http://try.websharper.com/snippet/0000IB

I am unsure if this is the only scenario that breaks.
_Update_: removing the last element has the same effect

**Comment by Tarmil** [comment]
Sorry about that, looks like our tests were insufficient.

I reverted 44fcc355 which introduced this issue: it is not needed anymore since we've changed how maps are serialized to JSON. This will be on NuGet very soon.

**Comment by Tarmil** [comment]
The fix is released on NuGet in v4.1.3.

**Comment by cata** [comment]
Thanks @Tarmil !
