### ISSUE TITLE
Optimize bundle command

### ISSUE THREAD

**Issue by Jand42** [dotnet-websharper/websharper#891]
The implementation of bundle/unpack/html build steps are carried over from WebSharper 3, that were executing them as from a separate build task, so they are taking only string arguments, and re-loading everything needed from dlls. Also these were exposed as command-line arguments.

This extra layer of wrapping (the `Command` abstraction in https://github.com/dotnet-websharper/websharper/blob/master/src/compiler/WebSharper.Compiler/commands/Commands.fs) is not needed when these are always only executed at the end of a single-step compilation.

In the case of bundling, this would cause a visible performance improvement, as the metadata can be passed along from memory instead of deserializing it again from dlls.

**Comment by Jand42** [comment]
Bundling was optimized away, but now it can only run after a full compilation. Html and unpac commands are still invokeable from command line with `wsfsc.exe html` and `wsfsc.exe unpack`.

**Comment by Jand42** [comment]
Additional optimization for compilation speed: when dead code elimination and source map generation are both off, bundling will use the pre-compiled JS output of referenced assemblies.

This results in a slightly larger output file, but much faster bundling step.

**Comment by granicz** [comment]
For future reference, be sure to document changes around command line options and paste the link to the updated documentation here. Thanks.

**Comment by Jand42** [comment]
@granicz There are no command line options changes related to these optimizations.

**Comment by Jand42** [comment]
@granicz Behavior of bundling from pre-compiled JS files is now documented at https://developers.websharper.com/docs/v4.1/fs/project-variables under the `WebSharperDeadCodeElimination` setting.
