### ISSUE TITLE
DateTime.TryParse too permissive

### ISSUE THREAD

**Issue by AlexPeret** [dotnet-websharper/websharper#893]
similar to this [issue](https://github.com/dotnet-websharper/websharper/issues/673), but on DateTime type.

For instance,

```
...
  let isValid,date = System.DateTime.TryParse "‎0‎/‎02‎/‎2018"
  Console.Log isValid
  Console.Log (data.ToShortDateString())
...
```

**Output:**

```
 true  // should print false
 02‎/‎12‎/‎2017
```

Changing the _uiCulture_ to "pt-BR" or "en-US" makes no difference.

Best Regards,
Alex

**Comment by AlexPeret** [comment]
I've tested on Firefox and it is working.

Turns out I was using Microsoft Edge and Date.parse is not returning NaN for invalid dates.

**Firefox (console):**
```
> Date.parse("0/02/2018")
< NaN
```
**MS Edge (console):**
```
> Date.parse("0/02/2018")
< 1512180000000
```

I'm closing this issue as it is not related to WebSharper.

**Comment by Jand42** [comment]
Thanks for the testing. There are some pending plans for `DateTime` improvements, for example string writing/parsing on the client #787
